### ISSUE TITLE
Build error "Module compiled with Swift 5.5 cannot be imported by the Swift 5.5.2 compiler"

### ISSUE THREAD

**Issue by YuriyRum** [vmwareairwatchsdk/vmware-wsone-sdk-flutter#4]
Hello,

I'm trying to build an iOS Flutter app with the workspaceone_sdk_flutter plugin version 22.1.0 and getting an error:

>   [ +163 ms] Swift Compiler Error (Xcode): Module compiled with Swift 5.5 cannot be imported by the Swift 5.5.2 compiler:
>   .../ios/.symlinks/plugins/workspaceone_sdk_flutter/ios/Framework/WorkspaceOneSDKBrid
>                       ge.framework/Modules/WorkspaceOneSDKBridge.swiftmodule/arm64-apple-ios.swiftmodule
>   .../dev/flutter/.pub-cache/hosted/pub.dartlang.org/workspaceone_sdk_flutter-22.1.0/ios/workspaceone_sdk_flutter/Swift
>                       WorkspaceoneSdkFlutterPlugin.swift:3:7
> 

**Prerequisites:**
- Xcode version 13.2.1
- Flutter version 2.10.1

**Flutter doctor results:**

[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6.2 20G314 darwin-arm)
    • Flutter version 2.10.1 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/urijrumancev/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.64.1)
    • VS Code 
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found! 

Could you please guide me. What am I doing wrong and how to fix it.

Thanks!

**Comment by akalghatgi** [comment]
Hi @YuriyRum 
Can you run your application  on Xcode 13.0 or lesser version.
Thanks 
Amit

**Comment by YuriyRum** [comment]
> Hi @YuriyRum Can you run your application on Xcode 13.0 or lesser version. Thanks Amit

Hi Amit,
It helped. Thanks!
BR,
Yuriy
